name: .NET Core 2

# defaults:
#   run:
#     working-directory: "Benday.Demo123"

on:
  workflow_dispatch:
    inputs:
      toEnvironment:
        description: 'deploy to which environment?'
        required: true
        default: 'dev'
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  AZURE_WEBAPP_NAME: bdcgithubactiondemo    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'Benday.Demo123/src/Benday.Demo123.WebUi'      # set this to the path to your web app project, defaults to the repository root
  PROJECT_TO_PUBLISH_PATH: 'Benday.Demo123/src/Benday.Demo123.WebUi'
  DOTNET_VERSION: '3.1.301'           # set this to the dot net version to use
  # 
  # I really want to do this but it doesn't seem to work
  # PUBLISH_TO_PATH: '$RUNNER_WORKSPACE/published'
  MYGITHUBTOKEN: '${{ github.token }}'
jobs:
  deploy:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Pa$$word
          MSSQL_PID: Standard
        ports:
        - 1433:1433        

    steps:      
    # - uses: actions/checkout@v2
    - run: |
        echo "toEnvironment: ${{ github.event.inputs.toEnvironment }}"
    - name: print environment vars
      run: env
    - name: print default working directory
      run: pwd
    - name: run an ls -l
      run: ls -lR
      working-directory: '${{ github.workspace }}'
    - name: Inspect contexts
      run: |
        echo ""
        echo "The github context is:"
        echo "${{ toJson(github) }}"
        echo ""
        echo "The job context is:"
        echo "${{ toJson(job) }}"
        echo ""
        echo "The steps context is:"
        echo "${{ toJson(steps) }}"
        echo ""
        echo "The runner context is:"
        echo "${{ toJson(runner) }}"
        echo ""
        echo "The strategy context is:"
        echo "${{ toJson(strategy) }}"
        echo ""
        echo "The matrix context is:"
        echo "${{ toJson(matrix) }}"
        echo ""
    #
    #
    - name: print environment vars again
      run: env
    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ env.DOTNET_VERSION }}
    # - name: Restore dotnet tools
    #   run: dotnet tool restore
    # - name: Install dependencies for .net core
    #   run: dotnet restore
    - name: Download artifact from a github workflow
      uses: benday/action-download-latest-artifact@v0.1
      with:
        token: '${{ env.MYGITHUBTOKEN }}'
        repository_owner: 'benday'
        repository_name: 'actionsdemo'
        workflow_name: '.NET Core'
        branch_name: 'master'
        download_path: '${{ github.workspace }}/temp'
        download_filename: 'actionsdemo-artifact.zip'
    - name: run an ls -l after download
      run: ls -lR
      working-directory: '${{ github.workspace }}'
    - name: mkdir for unzipped artifact
      run: mkdir '${{ github.workspace }}/actionsdemo-artifact'
    - name: unzip artifact
      run: unzip '${{ github.workspace }}/temp/actionsdemo-artifact.zip' -d '${{ github.workspace }}/actionsdemo-artifact'
    - name: run an ls -l after download
      run: ls -lR
      working-directory: '${{ github.workspace }}'